GET http://localhost:5000/api/users

###
GET http://localhost:5000/api/users/638e676f710ff240ae8f9ebe

###
POST  http://localhost:5000/api/users
Content-Type: application/json

{
    "first":"Brad",
    "last":"Schiff",
    "title":"Sr. Fullstack Dev",
    "website":"http://traversy-media.com"
}

###
DELETE http://localhost:5000/api/users/638f6b36bd2c014e8324aefe

###
PATCH http://localhost:5000/api/users/638e676f710ff240ae8f9ebe
Content-Type: application/json

{
    "last": "Schiff"
}

